version: '3.8'

services:
  app:
    build:
      context: app
      dockerfile: DockerFile
    image: event-planner-api:latest
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      - database
      - rabbitmq

  web-proxy:
    image: nginx:alpine3.21
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    command: ["nginx", "-g", "daemon off;"]

  rabbitmq:
    image: rabbitmq:4.0.6-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: on-failure

  database:
    image: postgres:15.11-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
    driver: local
  postgres_data:
    driver: local
